name: agro_picker_bloc
description: Shared Code for Producer and Consumer
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^1.1.1
  http: ^0.12.0+4
  bloc: ^4.0.0
  flutter_bloc: ^4.0.0
  cloud_firestore: ^0.13.5
  firebase_core: ^0.4.5
  firebase_auth: ^0.16.1
  google_sign_in: ^4.5.1
  meta: ^1.1.8
  rxdart: ^0.24.1
  json_annotation: ^3.0.1
  uuid: ^2.0.4
  firebase_storage: ^3.1.6
  image_picker: ^0.6.0+17

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.8.1
  json_serializable: ^3.3.0
